## ****************************************************************************
## ****************************************************************************
## Copyright SoC Design Research Group, All rights reserved.
## Electronics and Telecommunications Research Institute (ETRI)
##
## THESE DOCUMENTS CONTAIN CONFIDENTIAL INFORMATION AND KNOWLEDGE
## WHICH IS THE PROPERTY OF ETRI. NO PART OF THIS PUBLICATION IS
## TO BE USED FOR ANY OTHER PURPOSE, AND THESE ARE NOT TO BE
## REPRODUCED, COPIED, DISCLOSED, TRANSMITTED, STORED IN A RETRIEVAL
## SYSTEM OR TRANSLATED INTO ANY OTHER HUMAN OR COMPUTER LANGUAGE,
## IN ANY FORM, BY ANY MEANS, IN WHOLE OR IN PART, WITHOUT THE
## COMPLETE PRIOR WRITTEN PERMISSION OF ETRI.
## ****************************************************************************
## 2019-07-19 : Sukho Lee (shlee99@etri.re.kr)
## ****************************************************************************
## LPSDRAM Pin Map, 1.8V VCCO (Bank 64, 67)
## ****************************************************************************

create_clock -period 6.0   [get_ports LPSDR_CLK_FB]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets LPSDR_CLK_FB]

set_property PACKAGE_PIN        AK23    [get_ports {    LPSDR_A[0]        }]
set_property PACKAGE_PIN        AJ20    [get_ports {    LPSDR_A[1]        }]
set_property PACKAGE_PIN        AG21    [get_ports {    LPSDR_A[2]        }]
set_property PACKAGE_PIN        AJ25    [get_ports {    LPSDR_A[3]        }]
set_property PACKAGE_PIN        AH22    [get_ports {    LPSDR_A[4]        }]
set_property PACKAGE_PIN        AF20    [get_ports {    LPSDR_A[5]        }]
set_property PACKAGE_PIN        AJ24    [get_ports {    LPSDR_A[6]        }]
set_property PACKAGE_PIN        AJ23    [get_ports {    LPSDR_A[7]        }]
set_property PACKAGE_PIN        AH23    [get_ports {    LPSDR_A[8]        }]
set_property PACKAGE_PIN        AH21    [get_ports {    LPSDR_A[9]        }]
set_property PACKAGE_PIN        AK22    [get_ports {    LPSDR_A[10]       }]
set_property PACKAGE_PIN        AD20    [get_ports {    LPSDR_A[11]       }]
set_property PACKAGE_PIN        AJ21    [get_ports {    LPSDR_A[12]       }]

set_property PACKAGE_PIN        AE23    [get_ports {    LPSDR_BA[0]       }]
set_property PACKAGE_PIN        AG22    [get_ports {    LPSDR_BA[1]       }]

set_property PACKAGE_PIN        AN23    [get_ports {    LPSDR_DQ[0]       }]
set_property PACKAGE_PIN        AP24    [get_ports {    LPSDR_DQ[1]       }]
set_property PACKAGE_PIN        AL22    [get_ports {    LPSDR_DQ[2]       }]
set_property PACKAGE_PIN        AN24    [get_ports {    LPSDR_DQ[3]       }]
set_property PACKAGE_PIN        AL23    [get_ports {    LPSDR_DQ[4]       }]
set_property PACKAGE_PIN        AP25    [get_ports {    LPSDR_DQ[5]       }]
set_property PACKAGE_PIN        AM24    [get_ports {    LPSDR_DQ[6]       }]
set_property PACKAGE_PIN        AM25    [get_ports {    LPSDR_DQ[7]       }]
set_property PACKAGE_PIN        AP20    [get_ports {    LPSDR_DQ[8]       }]
set_property PACKAGE_PIN        AL20    [get_ports {    LPSDR_DQ[9]       }]
set_property PACKAGE_PIN        AP21    [get_ports {    LPSDR_DQ[10]      }]
set_property PACKAGE_PIN        AM20    [get_ports {    LPSDR_DQ[11]      }]
set_property PACKAGE_PIN        AN21    [get_ports {    LPSDR_DQ[12]      }]
set_property PACKAGE_PIN        AM22    [get_ports {    LPSDR_DQ[13]     }]
set_property PACKAGE_PIN        AN22    [get_ports {    LPSDR_DQ[14]      }]
set_property PACKAGE_PIN        AP23    [get_ports {    LPSDR_DQ[15]      }]
set_property PACKAGE_PIN        AN17    [get_ports {    LPSDR_DQ[16]      }]
set_property PACKAGE_PIN        AP18    [get_ports {    LPSDR_DQ[17]      }]
set_property PACKAGE_PIN        AM17    [get_ports {    LPSDR_DQ[18]      }]
set_property PACKAGE_PIN        AN18    [get_ports {    LPSDR_DQ[19]      }]
set_property PACKAGE_PIN        AL17    [get_ports {    LPSDR_DQ[20]      }]
set_property PACKAGE_PIN        AP19    [get_ports {    LPSDR_DQ[21]      }]
set_property PACKAGE_PIN        AL18    [get_ports {    LPSDR_DQ[22]      }]
set_property PACKAGE_PIN        AN19    [get_ports {    LPSDR_DQ[23]      }]
set_property PACKAGE_PIN        AN14    [get_ports {    LPSDR_DQ[24]      }]
set_property PACKAGE_PIN        AM14    [get_ports {    LPSDR_DQ[25]      }]
set_property PACKAGE_PIN        AP14    [get_ports {    LPSDR_DQ[26]      }]
set_property PACKAGE_PIN        AM15    [get_ports {    LPSDR_DQ[27]      }]
set_property PACKAGE_PIN        AP15    [get_ports {    LPSDR_DQ[28]      }]
set_property PACKAGE_PIN        AM16    [get_ports {    LPSDR_DQ[29]      }]
set_property PACKAGE_PIN        AN16    [get_ports {    LPSDR_DQ[30]      }]
set_property PACKAGE_PIN        AP16    [get_ports {    LPSDR_DQ[31]      }]

set_property PACKAGE_PIN        AL24    [get_ports {    LPSDR_DQM[0]      }]
set_property PACKAGE_PIN        AK21    [get_ports {    LPSDR_DQM[1]      }]
set_property PACKAGE_PIN        AM19    [get_ports {    LPSDR_DQM[2]      }]
set_property PACKAGE_PIN        AL14    [get_ports {    LPSDR_DQM[3]      }]

set_property PACKAGE_PIN        AK18    [get_ports {    LPSDR_CAS_N     }]
set_property PACKAGE_PIN        AG25    [get_ports {    LPSDR_CKE0      }]
set_property PACKAGE_PIN        AG24    [get_ports {    LPSDR_CKE1      }]
set_property PACKAGE_PIN        AK20    [get_ports {    LPSDR_CLK       }]
set_property PACKAGE_PIN        AM21    [get_ports {    LPSDR_CLK_FB    }]
set_property PACKAGE_PIN        AK25    [get_ports {    LPSDR_CS0_N     }]
set_property PACKAGE_PIN        AK15    [get_ports {    LPSDR_CS1_N    }]
set_property PACKAGE_PIN        AJ18    [get_ports {    LPSDR_RAS_N     }]
set_property PACKAGE_PIN        AK17    [get_ports {    LPSDR_WE_N      }]
#######################

set_property IOSTANDARD LVCMOS18        [get_ports {    LPSDR_A[0]        }]
set_property IOSTANDARD LVCMOS18        [get_ports {    LPSDR_A[1]        }]
set_property IOSTANDARD LVCMOS18        [get_ports {    LPSDR_A[2]        }]
set_property IOSTANDARD LVCMOS18        [get_ports {    LPSDR_A[3]        }]
set_property IOSTANDARD LVCMOS18        [get_ports {    LPSDR_A[4]        }]
set_property IOSTANDARD LVCMOS18        [get_ports {    LPSDR_A[5]        }]
set_property IOSTANDARD LVCMOS18        [get_ports {    LPSDR_A[6]        }]
set_property IOSTANDARD LVCMOS18        [get_ports {    LPSDR_A[7]        }]
set_property IOSTANDARD LVCMOS18        [get_ports {    LPSDR_A[8]        }]
set_property IOSTANDARD LVCMOS18        [get_ports {    LPSDR_A[9]        }]
set_property IOSTANDARD LVCMOS18        [get_ports {    LPSDR_A[10]       }]
set_property IOSTANDARD LVCMOS18        [get_ports {    LPSDR_A[11]       }]
set_property IOSTANDARD LVCMOS18        [get_ports {    LPSDR_A[12]       }]
set_property IOSTANDARD LVCMOS18        [get_ports {    LPSDR_BA[0]       }]
set_property IOSTANDARD LVCMOS18        [get_ports {    LPSDR_BA[1]       }]
set_property IOSTANDARD LVCMOS18        [get_ports {    LPSDR_DQ[0]       }]
set_property IOSTANDARD LVCMOS18        [get_ports {    LPSDR_DQ[1]       }]
set_property IOSTANDARD LVCMOS18        [get_ports {    LPSDR_DQ[2]       }]
set_property IOSTANDARD LVCMOS18        [get_ports {    LPSDR_DQ[3]       }]
set_property IOSTANDARD LVCMOS18        [get_ports {    LPSDR_DQ[4]       }]
set_property IOSTANDARD LVCMOS18        [get_ports {    LPSDR_DQ[5]       }]
set_property IOSTANDARD LVCMOS18        [get_ports {    LPSDR_DQ[6]       }]
set_property IOSTANDARD LVCMOS18        [get_ports {    LPSDR_DQ[7]       }]
set_property IOSTANDARD LVCMOS18        [get_ports {    LPSDR_DQ[8]       }]
set_property IOSTANDARD LVCMOS18        [get_ports {    LPSDR_DQ[9]       }]
set_property IOSTANDARD LVCMOS18        [get_ports {    LPSDR_DQ[10]      }]
set_property IOSTANDARD LVCMOS18        [get_ports {    LPSDR_DQ[11]      }]
set_property IOSTANDARD LVCMOS18        [get_ports {    LPSDR_DQ[12]      }]
set_property IOSTANDARD LVCMOS18        [get_ports {    LPSDR_DQ[13]      }]
set_property IOSTANDARD LVCMOS18        [get_ports {    LPSDR_DQ[14]      }]
set_property IOSTANDARD LVCMOS18        [get_ports {    LPSDR_DQ[15]      }]
set_property IOSTANDARD LVCMOS18        [get_ports {    LPSDR_DQ[16]      }]
set_property IOSTANDARD LVCMOS18        [get_ports {    LPSDR_DQ[17]      }]
set_property IOSTANDARD LVCMOS18        [get_ports {    LPSDR_DQ[18]      }]
set_property IOSTANDARD LVCMOS18        [get_ports {    LPSDR_DQ[19]      }]
set_property IOSTANDARD LVCMOS18        [get_ports {    LPSDR_DQ[20]      }]
set_property IOSTANDARD LVCMOS18        [get_ports {    LPSDR_DQ[21]      }]
set_property IOSTANDARD LVCMOS18        [get_ports {    LPSDR_DQ[22]      }]
set_property IOSTANDARD LVCMOS18        [get_ports {    LPSDR_DQ[23]      }]
set_property IOSTANDARD LVCMOS18        [get_ports {    LPSDR_DQ[24]      }]
set_property IOSTANDARD LVCMOS18        [get_ports {    LPSDR_DQ[25]      }]
set_property IOSTANDARD LVCMOS18        [get_ports {    LPSDR_DQ[26]      }]
set_property IOSTANDARD LVCMOS18        [get_ports {    LPSDR_DQ[27]      }]
set_property IOSTANDARD LVCMOS18        [get_ports {    LPSDR_DQ[28]      }]
set_property IOSTANDARD LVCMOS18        [get_ports {    LPSDR_DQ[29]      }]
set_property IOSTANDARD LVCMOS18        [get_ports {    LPSDR_DQ[30]      }]
set_property IOSTANDARD LVCMOS18        [get_ports {    LPSDR_DQ[31]      }]
set_property IOSTANDARD LVCMOS18        [get_ports {    LPSDR_DQM[0]      }]
set_property IOSTANDARD LVCMOS18        [get_ports {    LPSDR_DQM[1]      }]
set_property IOSTANDARD LVCMOS18        [get_ports {    LPSDR_DQM[2]      }]
set_property IOSTANDARD LVCMOS18        [get_ports {    LPSDR_DQM[3]      }]

set_property IOSTANDARD LVCMOS18        [get_ports {    LPSDR_CAS_N     }]
set_property IOSTANDARD LVCMOS18        [get_ports {    LPSDR_CKE0      }]
set_property IOSTANDARD LVCMOS18        [get_ports {    LPSDR_CKE1      }]
set_property IOSTANDARD LVCMOS18        [get_ports {    LPSDR_CLK       }]
set_property IOSTANDARD LVCMOS18        [get_ports {    LPSDR_CLK_FB    }]
set_property IOSTANDARD LVCMOS18        [get_ports {    LPSDR_CS0_N     }]
set_property IOSTANDARD LVCMOS18        [get_ports {    LPSDR_CS1_N     }]
set_property IOSTANDARD LVCMOS18        [get_ports {    LPSDR_RAS_N     }]
set_property IOSTANDARD LVCMOS18        [get_ports {    LPSDR_WE_N      }]

set_input_delay  -clock LPSDR_CLK_FB 4  [get_ports LPSDR_DQ[*]]
set_output_delay -clock LPSDR_CLK_FB 4  [get_ports LPSDR_CKE*]
set_output_delay -clock LPSDR_CLK_FB 4  [get_ports LPSDR_CS*_N]
set_output_delay -clock LPSDR_CLK_FB 4  [get_ports LPSDR_RAS_N] 
set_output_delay -clock LPSDR_CLK_FB 4  [get_ports LPSDR_CAS_N]
set_output_delay -clock LPSDR_CLK_FB 4  [get_ports LPSDR_WE_N]
set_output_delay -clock LPSDR_CLK_FB 4  [get_ports LPSDR_A[*]]
set_output_delay -clock LPSDR_CLK_FB 4  [get_ports LPSDR_BA[*]]
set_output_delay -clock LPSDR_CLK_FB 4  [get_ports LPSDR_DQM[*]]
set_output_delay -clock LPSDR_CLK_FB 4  [get_ports LPSDR_DQ[*]]

set_false_path -to [get_ports LPSDR_CLK]

